server:
  port: 8080

logging:
  level: info

providers:
  openai:
    api_key: "your-openai-api-key"
    api_url: "https://api.openai.com/v1"
    is_openai_compatible: true
  ollama:
    api_url: "http://localhost:11434"
    is_openai_compatible: true

models:
  gpt-4.1: openai
  llama2: ollama
  dummy-model: dummy
