version: '3.8'

services:
  llm-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      CONFIG_PATH: "/app/config.yml"
      OLLAMA_API_URL: "http://ollama:11434"
      SERVER_BASE_URL: "http://localhost:8081"
    networks:
      - llm-gateway-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - llm-gateway-network

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - llm-gateway-network

  ollama:
    image: ollama/ollama:0.10.0-rc1
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_DEBUG=1
    command: ["serve"]
    networks:
      - llm-gateway-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  grafana-data:
  ollama-data:

networks:
  llm-gateway-network:
    driver: bridge
