name: Docker build and push

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.meta.outputs.json }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/dtunikov/llm-gateway
          tags: |
            type=schedule
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch,suffix=-{{sha}}-${{ github.run_number }}
            type=ref,event=branch
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: dmitrii@spread.ai
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate Job Summary
        run: |
          echo "### :whale: Image version:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          for tag in "${{ steps.meta.outputs.tags }}"; do
            echo "${tag}" >> $GITHUB_STEP_SUMMARY
          done
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
